id: P1A39166D
initial_creation_type: ocr
source_metadata:
  volumes:
    1eba66bfc9344667a90693f9ae33a94a:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: དམིགས་པ་བརྟག་པའི་འགྲེལ་པ།
      total_pages: 1198
      volume_number: 97
